title = 'Delta Cooling Systems Limited'
# Navbar Menu Section
home = '//a[@href="/"]'
about = '//a[@href="/about"]'
services = '//a[@href="/services"]'
contact_us = '//a[@href="/contact-us"]'
# About section
about_header = '//h4'
about_subheader = '//h5'
contentAbout_p = '//p'
LearnMoreButton = '//button'
# Services section
services_title = '//h6'
summary_title = '//h7'
summary_section = '//div[@class="services-title"]/p'
business_range = '//div[@class="business-container"]/h2'
business_info = '//div[@class="business-container"]/p'
business_card = '//div[h3[@class="cardTitle"]]/h3'
services_info = '//div[@class="servicesAbout"]/h5'
services_image = '//div[@class="servicesImage"]'
# Why Choose Us Section
choose_section = '//div[@class="why-choose-us-container"]'
choose_title = '//div[@class="why-choose-us-container"]//h2'
# Contact Us Section
connect_heading = '//div[@class="contactInfo"]//h2'
phone_number = '//div[@class="contactDetails"]//p'
number_list = '//div[@class="contactDetails"]//li'
email_heading = '//div[@class="contactDetails"]//p'
email_list = '//div[@class="contactDetails"]//li'
website_heading = '//div[@class="contactDetails"]//p'
website_list= '//div[@class="contactDetails"]//li'
office_location= '//div[@class="contactDetails"]//p'
office_link= '//div[@class="contactDetails"]//p'
# Contact Form
fullname_heading = '//*[@id="contactPage"]/div[1]/div[2]/form/label[1]'
fullname_input = '//*[@id="contactPage"]/div[1]/div[2]/form/input[1]'
phone_heading = '//*[@id="contactPage"]/div[1]/div[2]/form/label[2]'
phone_input = '//*[@id="contactPage"]/div[1]/div[2]/form/input[2]'
email_heading = '//*[@id="contactPage"]/div[1]/div[2]/form/label[3]'
email_input = '//*[@id="contactPage"]/div[1]/div[2]/form/input[3]'
message_heading = '//*[@id="contactPage"]/div[1]/div[2]/form/label[4]'
message_input = '//*[@id="contactPage"]/div[1]/div[2]/form/textarea'
sendmessage_button = '//div[@class="submit"]//button'
